Repository coulterkyle/Project-3, pull requests merged in 2024-03, with the labels that each got.

#23 Enhancement | Repo Listing
  client/src/components/repoList.jsx
  client/src/components/ui/repo.jsx
  client/src/main.jsx
  client/src/pages/Repos.jsx
Labels: enhancement

#21 Enhancement | Issue Listing
  client/index.html
  client/src/assets/bootstrap.css
  client/src/components/Jumbotron/index.jsx
  client/src/components/issueList.jsx
  client/src/components/navigation.jsx
  client/src/components/ui/issue.jsx
  client/src/components/ui/navbar.jsx
  client/src/main.jsx
  client/src/pages/Error.jsx
  client/src/pages/Issues.jsx
Labels: enhancement

#24 Update database for more advanced issue storage
  client/src/pages/IssuesSearch.jsx
  server/models/Bounty.js
  server/models/Issue.js
  server/models/User.js
  server/models/Vote.js
  server/models/index.js
  server/schemas/resolvers.js
  server/schemas/typeDefs.js
Labels: enhancement

#29 Created seed data to create users
  server/package.json
  server/seeders/cleanDB.js
  server/seeders/seed.js
  server/seeders/userSeed.json
Labels: enhancement

#31 Modal
  client/index.html
  client/src/components/ui/issue.jsx
Labels: design

#33 Header navigation changes
  client/src/assets/bootstrap.min.css
  client/src/components/navigation.jsx
  client/src/components/ui/navbar.jsx
  client/src/main.jsx
  client/src/pages/Users.jsx
  client/src/utils/queries.js
  server/package.json
Labels: enhancement

#52 Created loop through each user to display.
  client/src/components/ui/user.jsx
  client/src/pages/Users.jsx
Labels: enhancement

#56 UI name style updates
  client/index.html
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/src/assets/BugDebugger-nobg-shadow.png
  client/src/assets/bootstrap.css
  client/src/components/navigation.jsx
  client/src/components/ui/footer.jsx
  client/src/components/ui/navbar.jsx
  client/src/pages/Contact.jsx
  client/src/pages/Home.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Users.jsx
Labels: enhancement, design

#57 UI name style updates
  client/src/assets/cancel.jpg
  client/src/assets/cancel.png
  client/src/assets/success.png
  client/src/components/myBounties.jsx
  client/src/pages/Cancel.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Success.jsx
Labels: design

#60 Profile display bounties
  client/src/components/ui/issue.jsx
  client/src/pages/Users.jsx
  client/src/utils/queries.js
Labels: enhancement
